# -*- coding: utf-8 -*-
"""bland_altman.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LYlbka1_eVDX6k8h8133WspHDSJ-QKJj
"""

import numpy as np
import matplotlib.pyplot as plt

def bland_altman(ppg, ecg):
    """
    Compute Bland-Altman statistics for two paired measurements.

    Parameters
    ----------
    ppg : array-like
        Measurements from PPG.
    ecg : array-like
        Measurements from ECG.

    Returns
    -------
    mean_vals : np.ndarray
        Mean of each paired measurement.
    diff : np.ndarray
        Difference of each pair (PPG - ECG).
    bias : float
        Mean difference.
    loa_upper : float
        Upper limit of agreement.
    loa_lower : float
        Lower limit of agreement.
    """
    ppg = np.asarray(ppg[:,1])
    ecg = np.asarray(ecg[:,1])

    if len(ppg) != len(ecg):
        raise ValueError("PPG and ECG must have the same length.")

    mean_vals = (ppg + ecg) / 2
    diff = ppg - ecg

    bias = np.mean(diff)
    sd = np.std(diff, ddof=1)   # sample standard deviation
    loa_upper = bias + 1.96 * sd
    loa_lower = bias - 1.96 * sd

    return mean_vals, diff, bias, loa_upper, loa_lower


def plot_bland_altman(ppg, ecg):
    mean_vals, diff, bias, loa_upper, loa_lower = bland_altman(ppg, ecg)

    plt.figure(figsize=(8, 5))
    plt.scatter(mean_vals, diff, alpha=0.7)
    plt.axhline(bias, linestyle='--', label=f'Bias = {bias:.3f}')
    plt.axhline(loa_upper, linestyle='--', label=f'Upper LoA = {loa_upper:.3f}')
    plt.axhline(loa_lower, linestyle='--', label=f'Lower LoA = {loa_lower:.3f}')

    plt.xlabel("Mean of PPG and ECG")
    plt.ylabel("Difference (PPG - ECG)")
    plt.title("Bland-Altman Plot")
    plt.legend()
    plt.grid(True)
    plt.show()